#!/bin/sh

initializeANSI(){
  esc=""
  reset="${esc}[0m"

  border="${reset}${esc}[38;5;232m"

  red="${esc}[38;5;160m";    redd="${esc}[38;5;124m"
  greyd="${reset}${esc}[38;5;235m"; grey="${reset}${esc}[38;5;250m"
  whited="${reset}${esc}[38;5;251m"; white="${reset}${esc}[38;5;255m"
  yellowd="${reset}${esc}[38;5;208m"; yellow="${reset}${esc}[38;5;214m"; yellowb="${reset}${esc}[38;5;220m"
  haird="${reset}${esc}[38;5;22m"; hair="${reset}${esc}[38;5;28m"; hairb="${reset}${esc}[38;5;34m"; hairw="${reset}${esc}[38;5;151m"
  skirtd="${reset}${esc}[38;5;19m"; skirt="${reset}${esc}[38;5;21m"; skirtb="${reset}${esc}[38;5;97m"
  snaked="${reset}${esc}[38;5;29m"; snake="${reset}${esc}[38;5;35m"
  shoed="${reset}${esc}[38;5;234m"; shoe="${reset}${esc}[38;5;237m"
  bandd="${reset}${esc}[38;5;19m"; band="${reset}${esc}[38;5;21m"; 
  brownd="${esc}[38;5;94m"; brown="${esc}[38;5;100m"; brownb="${esc}[38;5;136m";
  


  humand="${esc}[38;5;216m"; human="${esc}[38;5;223m"; humanb="${esc}[38;5;229m"
  eyed="${reset}${esc}[38;5;19m"; eye="${reset}${esc}[38;5;97m"
  boldon="${esc}[1m";    boldoff="${esc}[22m"
  italicson="${esc}[3m"; italicsoff="${esc}[23m"
  ulon="${esc}[4m";      uloff="${esc}[24m"
  invon="${esc}[7m";     invoff="${esc}[27m"
 
}

initializeANSI

cat << EOF
              ${border}████████████████████${reset}
          ${border}████${hair}████${hairb}██████████${hair}██████${border}████${reset}
        ${border}██${hair}██${hairb}██████████████████████${hair}████${border}██${reset}
      ${border}██${hair}██${hairb}████████████████████${haird}██${hairb}██${haird}██${hair}████${border}██${reset}
    ${border}██${hair}██${hairb}████████████████████${haird}██${redd}██${haird}██${redd}██${haird}██${hair}████${border}██${reset}
  ${border}██${hair}██${hairb}██████████████████████${haird}██${hair}██████${haird}██${hair}████${border}██${reset}
  ${border}██${hair}██${hairw}██${hairb}████████████████████${grey}██${white}██████${grey}██${hair}████${haird}██${border}██${reset}
${border}██${hair}██${hairb}████${hairw}██████${hairb}████████████████${grey}██████${hairb}████${hair}██${haird}██${border}██${reset}
${border}██${hairb}████████████${hair}██${hairw}████████${hairb}██${hairw}████████${hairb}██████${hair}██${haird}██${border}██${reset}
${border}██${hairb}████${hair}██${hairb}██████${haird}██${hairb}████████${hair}██${hairb}██████${hair}██${hairb}██████${hair}████${border}██${reset}
${border}██${hairb}██${hair}██${haird}██${hairb}██${hair}██${hairb}██${haird}██${hair}██${hairb}██████${haird}██${hairb}████████${hair}██${hairb}████${hair}████${border}██${reset}
${border}██${hair}██${haird}████${hairb}██${hair}██${border}████${haird}██${hair}██${hairb}██${hair}██${haird}████${hairb}██████${hair}██${hairb}████${hair}████${border}██${reset}
  ${haird}██${border}██${haird}██${hairb}██${haird}██${grey}██${border}██${humand}██${haird}██${hair}██${haird}██${border}████████${hairb}████${hair}██${hairb}██${hair}████${border}██${reset}
  ${border}██${reset}  ${border}██${hair}██${haird}██${grey}██${eyed}██${humanb}████${haird}██${humand}████${border}████${grey}██${border}██${hairb}██${hair}████${haird}██${hair}██${border}██${reset}
      ${border}██${hair}██${haird}██${white}██${eye}██${humanb}██████${humand}██${humanb}██${eyed}██${white}████${band}██${bandd}██${haird}██${hair}██${haird}██${hair}██${border}██${reset}
      ${border}██${hair}██${haird}██${humanb}██${eyed}██${humanb}██████████${eye}██${eyed}██${white}██${band}██${bandd}██${border}██${haird}████${hair}██${border}██${reset}
      ${border}██${hair}██${haird}██${human}██${humanb}████████████${eyed}████${humanb}██${band}██${bandd}██${border}██${haird}██████${border}██${reset}
        ${border}██${hair}██${haird}██${humanb}████████████████${human}██${grey}██${white}██${border}██${haird}██████${border}██${reset}
        ${border}██${hair}██${haird}██${border}██${human}██████████████${hair}██${hairb}██${hair}██${border}██${haird}████${border}██${reset}
        ${border}██${haird}████${human}██${grey}██${skirt}██${white}██${grey}████${greyd}██${humand}██${haird}██${hairb}██${haird}██${border}██${haird}████${border}██${reset}
        ${border}██${haird}██${grey}██${border}██${white}██${skirt}██${white}██████${grey}██${greyd}██${haird}██${hair}██${border}████${haird}██${border}██${reset}
          ${border}██${grey}██${border}██${white}██${skirtd}██${white}██████${grey}██${greyd}██${grey}██${haird}██${grey}██${border}████${reset}
        ${border}██${grey}██${border}██${skirtd}██${skirt}██████${skirtd}██████${border}██${white}████${grey}██${border}██${reset}
        ${border}████${skirtd}██${skirtb}██${skirt}██████${skirtb}██${skirtd}████${border}██${white}████${skirt}██${grey}██${border}██${reset}
        ${border}██${skirtd}██${skirt}██████${skirtb}██${skirt}██████${skirtd}██${border}██${white}██${skirt}██${white}██${grey}██${border}██${reset}
        ${border}██${grey}██${skirtb}██${skirt}████████████${skirtb}██${skirtd}██${grey}██${white}██${grey}██${skirtd}██${border}██${reset}
          ${border}██${white}████████${skirt}██${skirtb}██${skirt}██████${skirtd}██████${grey}██${border}██${reset}
            ${border}██${shoe}██${shoed}██${border}██${white}████████████${grey}████${border}██${reset}
              ${border}████${reset}  ${border}████████${shoe}██${shoed}██${border}████${reset}
                            ${border}████${reset}
EOF